name: benzenetest2
channels:
  - defaults
  - conda-forge
  - gpytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alsa-lib=1.2.14
  - anyio=4.12.0
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.4.0
  - asttokens=3.0.1
  - async-lru=2.0.5
  - attr=2.5.2
  - attrs=25.4.0
  - babel=2.17.0
  - backports.zstd=1.2.0
  - beautifulsoup4=4.14.3
  - bleach=6.3.0
  - bleach-with-css=6.3.0
  - botorch=0.16.1
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.11.14
  - cuda-crt-tools=12.9.86
  - cuda-cudart=12.9.79
  - cuda-cudart_linux-64=12.9.79
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.9.79
  - cuda-nvcc-tools=12.9.86
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.9.86
  - cuda-nvtx=12.9.79
  - cuda-nvvm-tools=12.9.86
  - cuda-version=12.9
  - cudnn=9.10.2.21
  - cusparselt=0.7.0.0
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.8.19
  - decorator=5.2.1
  - defusedxml=0.7.1
  - double-conversion=3.3.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - expat=2.7.3
  - filelock=3.20.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - fqdn=1.5.1
  - freetype=2.14.1
  - fsspec=2025.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gpytorch=1.14.3
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=9.0.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.11
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - isoduration=20.11.0
  - jaxtyping=0.3.2
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json5=0.12.1
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.3.0
  - jupyter_client=8.7.0
  - jupyter_core=5.9.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.5.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.3.1
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240722.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libclang-cpp18.1=18.1.8
  - libclang13=21.1.0
  - libcublas=12.9.1.4
  - libcudnn=9.10.2.21
  - libcudnn-dev=9.10.2.21
  - libcudss0=0.4.0.2
  - libcufft=11.4.1.4
  - libcufile=1.14.1.1
  - libcups=2.3.3
  - libcurand=10.3.10.19
  - libcusolver=11.7.5.82
  - libcusparse=12.5.10.65
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.80.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libllvm18=18.1.8
  - libllvm20=20.1.8
  - libllvm21=21.1.0
  - libmagma=2.8.0
  - libnl=3.11.0
  - libnsl=2.0.0
  - libnvjitlink=12.9.86
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libpciaccess=0.18
  - libpng=1.6.53
  - libpq=16.11
  - libprotobuf=5.28.3
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libudev1=258.3
  - libuuid=1.41.5
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.11.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - linear_operator=0.6
  - markupsafe=3.0.3
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - mistune=3.1.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.28.9.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.6.1
  - nomkl=1.0
  - notebook=7.5.1
  - notebook-shim=0.2.4
  - numpy=2.3.5
  - openjpeg=2.5.3
  - openssl=3.6.0
  - opt_einsum=3.4.0
  - optree=0.18.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pcre2=10.43
  - pexpect=4.9.0
  - pillow=11.3.0
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prometheus_client=0.23.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyre-extensions=0.0.32
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=2.0.7
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - rdma-core=60.0
  - readline=8.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.30.0
  - scikit-learn=1.8.0
  - scipy=1.16.3
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sniffio=1.3.1
  - soupsieve=2.8.1
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.5.1
  - tk=8.6.15
  - tomli=2.3.0
  - tornado=6.5.4
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.2.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - urllib3=2.6.2
  - wadler-lindig=0.1.7
  - wayland=1.23.1
  - wcwidth=0.2.14
  - webcolors=25.10.0
  - webencodings=0.5.1
  - websocket-client=1.9.0
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.6
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - hebz==0.0.9
      - importlib==1.0.4
prefix: /home/sutirthapaul/miniconda3/envs/benzenetest2
